"""add friend listings

Revision ID: 15b84e87b6d0
Revises: 698c0076ddbf
Create Date: 2026-07-22 13:26:51.749536
"""

from alembic import op
import sqlalchemy as sa


revision = '15b84e87b6d0'
down_revision = '698c0076ddbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_listings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('roblox_user_id', sa.BigInteger(), nullable=False),
    sa.Column('roblox_username', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_friend_listings'))
    )
    with op.batch_alter_table('friend_listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_friend_listings_telegram_id'), ['telegram_id'], unique=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('friend_listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_friend_listings_telegram_id'))

    op.drop_table('friend_listings')
    # ### end Alembic commands ###
