"""add user nickname

Revision ID: 698c0076ddbf
Revises: d96285898706
Create Date: 2026-07-22 13:15:20.699368
"""

from alembic import op
import sqlalchemy as sa


revision = '698c0076ddbf'
down_revision = 'd96285898706'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
