"""add user roblox_user_id

Revision ID: cd2b18661e4f
Revises: 15b84e87b6d0
Create Date: 2026-07-22 13:56:05.159577
"""

from alembic import op
import sqlalchemy as sa


revision = 'cd2b18661e4f'
down_revision = '15b84e87b6d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('roblox_user_id', sa.BigInteger(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('roblox_user_id')

    # ### end Alembic commands ###
